"""添加Comment模型

Revision ID: 4ef4d42900b0
Revises: 3647b8758264
Create Date: 2020-08-02 17:38:43.023251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef4d42900b0'
down_revision = '3647b8758264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'subject_id')
    # ### end Alembic commands ###
